( function ( window ){
	"use strict";

	window.CONST = {};

	// APPLICATION
	CONST.APPLICATION_READY = 'APPLICATION_READY';

	// UI EVENTS
	CONST.UI_CHORD_SELECT   = 'UI_CHORD_SELECT';

	// DATA EVENTS
	CONST.DATA_DIR_SET      = 'DATA_DIR_SET';
	CONST.DATA_KEY_SET      = 'DATA_KEY_SET';
	CONST.DATA_NOTES_SET    = 'DATA_NOTES_SET';

	// CONFIGURATION
	CONST.UI_BIND_TYPE      = 'touchend click';

	// DATA PROPERTIES
	CONST.DIR_DRAW          = 'DIR_DRAW';
	CONST.DIR_PUSH          = 'DIR_PUSH';

}(window));
